locale: "en-US"
title: "GNBT 120: Analysis of Genomes"
name: "Daniel Koenig"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
sidebar:
  - Syllabus
  - Schedule
